name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Python and C++ code
    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v4

      # 2. Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 3. Install Python dependencies
      - name: Install Python requirements
        run: pip install -r api/requirements.txt

      # 4. Run Python tests with coverage and generate coverage.xml
      - name: Run Python tests and collect coverage
        run: |
          pytest --cov --cov-report=xml --cov-report=term
          # This produces coverage.xml (flagged for Python)

      # 5. Upload Python coverage to Codecov with the flag "python"
      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: python
          fail_ci_if_error: true

      # 6. Install dependencies for C++ coverage
      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov

      # 7. Build C++ tests with coverage flags
      - name: Build C++ tests
        run: |
          cd api_c
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make

      # 8. Run C++ tests
      - name: Run C++ tests
        run: |
          cd api_c/build
          # Adjust these paths/executables as per your build output
          ./calculator/test-calculator
          ./smiles/test-smiles

      # 9. Generate C++ coverage report using lcov
      - name: Generate C++ coverage
        run: |
          cd api_c/build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      # 10. Upload C++ coverage to Codecov with the flag "c++"
      - name: Upload C++ coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: api_c/build/coverage.info
          flags: "c++"
          fail_ci_if_error: true
